apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-trident-nvme-storage-config
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CA Security Assessment and Authorization
    policy.open-cluster-management.io/controls: CA-2 Security Assessments, CA-7 Continuous Monitoring
spec:
{{- if (($.Values.autoshift).dryRun) }}
  remediationAction: inform
{{- end }}
  dependencies:
    - name: policy-trident-orchestrator
      namespace: {{ .Values.policy_namespace }}
      apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: Policy
    - name: policy-trident-machineconfigs
      namespace: {{ .Values.policy_namespace }}
      apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: Policy
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: trident-backend-nvme-storage-config
        spec:
          remediationAction: enforce
          severity: high
          object-templates-raw: |
            {{ "{{hub" }} $configs := index (index (fromConfigMap "{{ $.Values.policy_namespace }}" (print .ManagedClusterName ".rendered-config") "config" | default "" | fromYaml) "trident" | default dict) {{ "hub}}" }}
            {{ "{{hub" }} if and $configs.storage $configs.storage.nvme {{ "hub}}" }}
            {{ "{{hub" }} range $storage := $configs.storage.nvme {{ "hub}}" }}
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: trident.netapp.io/v1
                kind: TridentBackendConfig
                metadata:
                  name: "{{ "{{hub" }} $storage.backendName {{ "hub}}" }}"
                  namespace: trident
                spec:
                  version: 1
                  backendName: "{{ "{{hub" }} $storage.backendName {{ "hub}}" }}"
                  storageDriverName: ontap-san
                  managementLIF: "{{ "{{hub" }} $storage.svmLif {{ "hub}}" }}"
                  sanType: nvme
                  credentials:
                    name: "{{ "{{hub" }} $storage.secretName {{ "hub}}" }}"
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: storage.k8s.io/v1
                kind: StorageClass
                metadata:
                  name: "{{ "{{hub" }} $storage.storageClassName {{ "hub}}" }}"
                  {{ "{{hub" }}- if eq ($storage.defaultStorageClass | default "false") "true" {{ "hub}}" }}
                  annotations:
                    storageclass.kubernetes.io/is-default-class: 'true'
                  {{ "{{hub" }}- end {{ "hub}}" }}
                provisioner: csi.trident.netapp.io
                parameters:
                  backendType: "ontap-san"
                  storagePools: "{{ "{{hub" }} $storage.backendName {{ "hub}}" }}:.*"
                  fsType: "{{ "{{hub" }} $storage.fsType | default "ext4" {{ "hub}}" }}"
                mountOptions:
                  - discard
                allowVolumeExpansion: true
            {{ "{{hub" }} end {{ "hub}}" }}
            {{ "{{hub" }} end {{ "hub}}" }}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-trident-nvme-storage-config
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := .Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := .Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/trident'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-trident-nvme-storage-config
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: placement-policy-trident-nvme-storage-config
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-trident-nvme-storage-config
    apiGroup: policy.open-cluster-management.io
    kind: Policy
